export type Review = {
    name: string; // applicant name
    id: string; // applicant id
    image: string;
    terrain: number;
    technical: number;
    learning: number;
    personal: number;
    finalAssessment: string;
    notes: string;
    finalScore: number;
    evaluatorName: string;
    evaluatorId: string;
    date: string;
    path: string;
};

export const mockReviews: Review[] = [
    {
        "name": "אורי לוי",
        "id": "834921",
        "image": "",
        "terrain": 2.6,
        "technical": 2.8,
        "learning": 2.7,
        "personal": 3.2,
        "finalAssessment": "מועמד מצטיין",
        "notes": "פוטנציאל גבוה",
        "finalScore": 1.1,
        "evaluatorName": "נדב שגב",
        "evaluatorId": "929884",
        "date": "31-01-2024 19:46",
        "path": "אביה 1"
    },
    {
        "name": "אורי לוי",
        "id": "834921",
        "image": "",
        "terrain": 2.5,
        "technical": 3.4,
        "learning": 4.2,
        "personal": 1.8,
        "finalAssessment": "מועמד מצטיין",
        "notes": "",
        "finalScore": 4.0,
        "evaluatorName": "גיא בן עמי",
        "evaluatorId": "148455",
        "date": "29-06-2024 21:12",
        "path": "אביה 1"
    },
    {
        "name": "אורי לוי",
        "id": "834921",
        "image": "",
        "terrain": 3.6,
        "technical": 4.9,
        "learning": 4.6,
        "personal": 1.5,
        "finalAssessment": "מועמד מצטיין",
        "notes": "קשיים בשטח",
        "finalScore": 3.0,
        "evaluatorName": "יהב ברק",
        "evaluatorId": "745832",
        "date": "11-12-2024 22:09",
        "path": "אביה 1"
    },
    {
        "name": "יואב כהן",
        "id": "843210",
        "image": "",
        "terrain": 3.3,
        "technical": 2.3,
        "learning": 2.0,
        "personal": 3.7,
        "finalAssessment": "מועמד מצטיין",
        "notes": "קשיים בשטח",
        "finalScore": 4.8,
        "evaluatorName": "אור רוזן",
        "evaluatorId": "689945",
        "date": "11-04-2024 16:55",
        "path": "נקרות"
    },
    {
        "name": "יואב כהן",
        "id": "843210",
        "image": "",
        "terrain": 1.6,
        "technical": 1.5,
        "learning": 2.5,
        "personal": 4.6,
        "finalAssessment": "דרוש שיפור",
        "notes": "",
        "finalScore": 3.3,
        "evaluatorName": "מאור ישראלי",
        "evaluatorId": "872700",
        "date": "18-04-2024 05:04",
        "path": "חצרה 1"
    },
    {
        "name": "יואב כהן",
        "id": "843210",
        "image": "",
        "terrain": 4.5,
        "technical": 3.0,
        "learning": 4.2,
        "personal": 4.9,
        "finalAssessment": "דרוש שיפור",
        "notes": "קשיים בשטח",
        "finalScore": 1.9,
        "evaluatorName": "גיא בן עמי",
        "evaluatorId": "148455",
        "date": "24-06-2024 05:04",
        "path": "קרני חיטים 1"
    },
    {
        "name": "איתן ישראלי",
        "id": "842398",
        "image": "",
        "terrain": 1.0,
        "technical": 1.5,
        "learning": 1.5,
        "personal": 3.1,
        "finalAssessment": "מועמד מצטיין",
        "notes": "יכולת למידה מרשימה",
        "finalScore": 2.0,
        "evaluatorName": "טל מרציאנו",
        "evaluatorId": "772596",
        "date": "07-12-2024 16:19",
        "path": "הקפה רמות מנשה"
    },
    {
        "name": "איתן ישראלי",
        "id": "842398",
        "image": "",
        "terrain": 1.2,
        "technical": 3.7,
        "learning": 3.5,
        "personal": 1.5,
        "finalAssessment": "מועמד מצטיין",
        "notes": "פוטנציאל גבוה",
        "finalScore": 3.1,
        "evaluatorName": "עידן לוי",
        "evaluatorId": "395346",
        "date": "15-12-2024 23:11",
        "path": "חצרה 1"
    },
    {
        "name": "איתן ישראלי",
        "id": "842398",
        "image": "",
        "terrain": 1.1,
        "technical": 3.0,
        "learning": 3.4,
        "personal": 4.5,
        "finalAssessment": "מועמד טוב",
        "notes": "יכולת למידה מרשימה",
        "finalScore": 2.0,
        "evaluatorName": "יהב ברק",
        "evaluatorId": "745832",
        "date": "26-09-2024 10:35",
        "path": "הקפה רמות מנשה"
    },
    {
        "name": "רועי פז",
        "id": "832198",
        "image": "",
        "terrain": 3.6,
        "technical": 1.1,
        "learning": 2.4,
        "personal": 4.0,
        "finalAssessment": "דרוש שיפור",
        "notes": "יכולת למידה מרשימה",
        "finalScore": 2.5,
        "evaluatorName": "תומר ברק",
        "evaluatorId": "204094",
        "date": "21-03-2024 12:05",
        "path": "חצרה 2"
    },
    {
        "name": "רועי פז",
        "id": "832198",
        "image": "",
        "terrain": 4.3,
        "technical": 2.6,
        "learning": 1.3,
        "personal": 2.0,
        "finalAssessment": "דרוש שיפור",
        "notes": "קשיים בשטח",
        "finalScore": 1.1,
        "evaluatorName": "אבירם רוזן",
        "evaluatorId": "578679",
        "date": "13-03-2024 00:02",
        "path": "חצרה 1"
    },
    {
        "name": "רועי פז",
        "id": "832198",
        "image": "",
        "terrain": 1.4,
        "technical": 1.1,
        "learning": 2.9,
        "personal": 3.9,
        "finalAssessment": "מועמד מצטיין",
        "notes": "קשיים בשטח",
        "finalScore": 4.9,
        "evaluatorName": "נדב שגב",
        "evaluatorId": "929884",
        "date": "04-06-2024 01:36",
        "path": "רמות מנשה 2"
    },
    {
        "name": "רן אדרי",
        "id": "849302",
        "image": "",
        "terrain": 1.2,
        "technical": 1.3,
        "learning": 1.5,
        "personal": 4.6,
        "finalAssessment": "מועמד מצטיין",
        "notes": "פוטנציאל גבוה",
        "finalScore": 1.7,
        "evaluatorName": "יהב ברק",
        "evaluatorId": "745832",
        "date": "03-01-2024 11:50",
        "path": "קרני חיטים 1"
    },
    {
        "name": "רן אדרי",
        "id": "849302",
        "image": "",
        "terrain": 4.4,
        "technical": 2.1,
        "learning": 4.3,
        "personal": 1.0,
        "finalAssessment": "מועמד טוב",
        "notes": "פוטנציאל גבוה",
        "finalScore": 4.6,
        "evaluatorName": "אור רוזן",
        "evaluatorId": "689945",
        "date": "20-10-2024 16:48",
        "path": "אביה 1"
    },
    {
        "name": "רן אדרי",
        "id": "849302",
        "image": "",
        "terrain": 2.0,
        "technical": 2.9,
        "learning": 2.4,
        "personal": 4.9,
        "finalAssessment": "דרוש שיפור",
        "notes": "",
        "finalScore": 4.7,
        "evaluatorName": "גיא בן עמי",
        "evaluatorId": "148455",
        "date": "25-03-2024 11:37",
        "path": "חצרה 2"
    },
    {
        "name": "דניאל פרידמן",
        "id": "123456",
        "image": "",
        "terrain": 4.4,
        "technical": 4.4,
        "learning": 4.2,
        "personal": 1.1,
        "finalAssessment": "דרוש שיפור",
        "notes": "קשיים בשטח",
        "finalScore": 1.6,
        "evaluatorName": "אבירם רוזן",
        "evaluatorId": "578679",
        "date": "31-05-2024 05:58",
        "path": "חצרה 1"
    },
    {
        "name": "דניאל פרידמן",
        "id": "123456",
        "image": "",
        "terrain": 3.0,
        "technical": 4.2,
        "learning": 1.3,
        "personal": 4.7,
        "finalAssessment": "מועמד טוב",
        "notes": "יכולת למידה מרשימה",
        "finalScore": 2.1,
        "evaluatorName": "תומר ברק",
        "evaluatorId": "204094",
        "date": "05-12-2024 10:55",
        "path": "הקפה רמות מנשה"
    },
    {
        "name": "דניאל פרידמן",
        "id": "123456",
        "image": "",
        "terrain": 1.7,
        "technical": 3.0,
        "learning": 1.7,
        "personal": 3.3,
        "finalAssessment": "דרוש שיפור",
        "notes": "פוטנציאל גבוה",
        "finalScore": 1.8,
        "evaluatorName": "אילון שגב",
        "evaluatorId": "697792",
        "date": "23-10-2024 18:10",
        "path": "נקרות"
    },
    {
        "name": "רועי ברקוביץ",
        "id": "234567",
        "image": "",
        "terrain": 3.5,
        "technical": 1.4,
        "learning": 4.8,
        "personal": 2.2,
        "finalAssessment": "מועמד מצטיין",
        "notes": "קשיים בשטח",
        "finalScore": 4.6,
        "evaluatorName": "אילון שגב",
        "evaluatorId": "697792",
        "date": "25-01-2024 02:46",
        "path": "רמות מנשה 1"
    },
    {
        "name": "רועי ברקוביץ",
        "id": "234567",
        "image": "",
        "terrain": 1.4,
        "technical": 3.2,
        "learning": 4.1,
        "personal": 3.6,
        "finalAssessment": "דרוש שיפור",
        "notes": "",
        "finalScore": 3.1,
        "evaluatorName": "אור רוזן",
        "evaluatorId": "689945",
        "date": "31-08-2024 02:12",
        "path": "רמות מנשה 1"
    },
    {
        "name": "רועי ברקוביץ",
        "id": "234567",
        "image": "",
        "terrain": 1.9,
        "technical": 4.0,
        "learning": 1.5,
        "personal": 2.1,
        "finalAssessment": "מועמד טוב",
        "notes": "קשיים בשטח",
        "finalScore": 4.4,
        "evaluatorName": "אסף רוטמן",
        "evaluatorId": "340208",
        "date": "01-11-2024 10:28",
        "path": "חצרה 1"
    },
    {
        "name": "עידו רוזנברג",
        "id": "345678",
        "image": "",
        "terrain": 5.0,
        "technical": 3.0,
        "learning": 4.2,
        "personal": 2.5,
        "finalAssessment": "דרוש שיפור",
        "notes": "",
        "finalScore": 4.8,
        "evaluatorName": "עידן לוי",
        "evaluatorId": "395346",
        "date": "25-04-2024 11:21",
        "path": "חצרה 2"
    },
    {
        "name": "עידו רוזנברג",
        "id": "345678",
        "image": "",
        "terrain": 2.2,
        "technical": 3.4,
        "learning": 2.7,
        "personal": 4.4,
        "finalAssessment": "מועמד טוב",
        "notes": "",
        "finalScore": 2.1,
        "evaluatorName": "אילון שגב",
        "evaluatorId": "697792",
        "date": "03-07-2024 04:12",
        "path": "נקרות"
    },
    {
        "name": "עידו רוזנברג",
        "id": "345678",
        "image": "",
        "terrain": 3.4,
        "technical": 1.4,
        "learning": 2.5,
        "personal": 4.5,
        "finalAssessment": "מועמד מצטיין",
        "notes": "קשיים בשטח",
        "finalScore": 4.2,
        "evaluatorName": "אבירם רוזן",
        "evaluatorId": "578679",
        "date": "06-04-2024 21:34",
        "path": "אביה 1"
    },
    {
        "name": "אורי כהן",
        "id": "456789",
        "image": "",
        "terrain": 4.4,
        "technical": 1.0,
        "learning": 2.7,
        "personal": 1.4,
        "finalAssessment": "מועמד מצטיין",
        "notes": "פוטנציאל גבוה",
        "finalScore": 3.9,
        "evaluatorName": "יהב ברק",
        "evaluatorId": "745832",
        "date": "15-09-2024 22:34",
        "path": "חצרה 2"
    },
    {
        "name": "אורי כהן",
        "id": "456789",
        "image": "",
        "terrain": 1.8,
        "technical": 3.1,
        "learning": 3.1,
        "personal": 3.8,
        "finalAssessment": "דרוש שיפור",
        "notes": "",
        "finalScore": 1.8,
        "evaluatorName": "אבירם רוזן",
        "evaluatorId": "578679",
        "date": "03-07-2024 23:04",
        "path": "רמות מנשה 1"
    },
    {
        "name": "אורי כהן",
        "id": "456789",
        "image": "",
        "terrain": 1.4,
        "technical": 1.5,
        "learning": 2.2,
        "personal": 5.0,
        "finalAssessment": "דרוש שיפור",
        "notes": "יכולת למידה מרשימה",
        "finalScore": 4.9,
        "evaluatorName": "תומר ברק",
        "evaluatorId": "204094",
        "date": "11-06-2024 13:58",
        "path": "אביה 1"
    }
];