export type Applicant = {
    name: string;
    id: string;
    image: string;
    rank: number;
    status: string;
    score: number;
    notes: string;
    unit: 'סיירת צנחנים' | 'אגוז' | 'מגלן' | 'דובדבן';
};

export const mockApplicants: Applicant[] = [
    {
        name: 'אורי לוי',
        id: '834921',
        image: '',
        rank: 1,
        status: 'עבר',
        score: 4.8,
        notes: 'מצטיין צוות',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'יואב כהן',
        id: '843210',
        image: '',
        rank: 2,
        status: 'עבר',
        score: 4.6,
        notes: 'מועמד מוביל לקצונה בצוות',
        unit: 'אגוז',
    },
    {
        name: 'איתן ישראלי',
        id: '842398',
        image: '',
        rank: 3,
        status: 'לא עבר',
        score: 3.1,
        notes: 'קושי בעבודת צוות',
        unit: 'מגלן',
    },
    {
        name: 'רועי פז',
        id: '832198',
        image: '',
        rank: 4,
        status: 'עבר',
        score: 4.0,
        notes: 'פוטנציאל גבוה',
        unit: 'דובדבן',
    },
    {
        name: 'רן אדרי',
        id: '849302',
        image: '',
        rank: 5,
        status: 'לא עבר',
        score: 2.9,
        notes: 'בעיות משמעת',
        unit: 'אגוז',
    },
    {
        name: 'דניאל פרידמן',
        id: '123456',
        image: '',
        rank: 6,
        status: 'עבר',
        score: 3.5,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'רועי ברקוביץ',
        id: '234567',
        image: '',
        rank: 7,
        status: 'עבר',
        score: 4.1,
        notes: 'מועמד מצטיין',
        unit: 'מגלן',
    },
    {
        name: 'עידו רוזנברג',
        id: '345678',
        image: '',
        rank: 8,
        status: 'לא עבר',
        score: 2.3,
        notes: 'דרוש שיפור',
        unit: 'אגוז',
    },
    {
        name: 'אורי כהן',
        id: '456789',
        image: '',
        rank: 9,
        status: 'עבר',
        score: 4.7,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'טליה לוי',
        id: '567890',
        image: '',
        rank: 10,
        status: 'עבר',
        score: 3.9,
        notes: 'מועמד מבטיח',
        unit: 'מגלן',
    },
    {
        name: 'עומרי שמואלי',
        id: '678901',
        image: '',
        rank: 11,
        status: 'לא עבר',
        score: 2.8,
        notes: 'לא עמד בציפיות',
        unit: 'אגוז',
    },
    {
        name: 'תמר פרץ',
        id: '789012',
        image: '',
        rank: 12,
        status: 'עבר',
        score: 4.2,
        notes: 'התקדמות מרשימה',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'יונתן אברהם',
        id: '890123',
        image: '',
        rank: 13,
        status: 'עבר',
        score: 3.6,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'שקד גולדשטיין',
        id: '901234',
        image: '',
        rank: 14,
        status: 'לא עבר',
        score: 2.4,
        notes: 'דרוש שיפור',
        unit: 'מגלן',
    },
    {
        name: 'אדווה מימון',
        id: '012345',
        image: '',
        rank: 15,
        status: 'עבר',
        score: 4.3,
        notes: '',
        unit: 'אגוז',
    },
    {
        name: 'רועי ברזילי',
        id: '135790',
        image: '',
        rank: 16,
        status: 'עבר',
        score: 3.8,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'עומרי דניאל',
        id: '246801',
        image: '',
        rank: 17,
        status: 'לא עבר',
        score: 2.7,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'עידן טל',
        id: '357912',
        image: '',
        rank: 18,
        status: 'עבר',
        score: 4.5,
        notes: 'מועמד מצטיין',
        unit: 'מגלן',
    },
    {
        name: 'ליאב שחר',
        id: '468023',
        image: '',
        rank: 19,
        status: 'עבר',
        score: 3.4,
        notes: '',
        unit: 'אגוז',
    },
    {
        name: 'אורי נמרוד',
        id: '579134',
        image: '',
        rank: 20,
        status: 'לא עבר',
        score: 2.6,
        notes: 'דרוש שיפור',
        unit: 'דובדבן',
    },
    {
        name: 'טל כהן',
        id: '680245',
        image: '',
        rank: 21,
        status: 'עבר',
        score: 4.0,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'רועי מזרחי',
        id: '791356',
        image: '',
        rank: 22,
        status: 'עבר',
        score: 3.7,
        notes: '',
        unit: 'מגלן',
    },
    {
        name: 'יוסי לוי',
        id: '802467',
        image: '',
        rank: 23,
        status: 'לא עבר',
        score: 2.5,
        notes: 'קושי בעבודת צוות',
        unit: 'אגוז',
    },
    {
        name: 'רון אוחיון',
        id: '913578',
        image: '',
        rank: 24,
        status: 'עבר',
        score: 4.1,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'עידו רפאלי',
        id: '024689',
        image: '',
        rank: 25,
        status: 'עבר',
        score: 3.3,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'תובל רוזן',
        id: '135790',
        image: '',
        rank: 26,
        status: 'לא עבר',
        score: 2.2,
        notes: 'דרוש שיפור',
        unit: 'מגלן',
    },
    {
        name: 'אפרת ברק',
        id: '246801',
        image: '',
        rank: 27,
        status: 'עבר',
        score: 4.6,
        notes: '',
        unit: 'אגוז',
    },
    {
        name: 'רוני סלע',
        id: '357912',
        image: '',
        rank: 28,
        status: 'עבר',
        score: 3.2,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'דניאל חזן',
        id: '468023',
        image: '',
        rank: 29,
        status: 'לא עבר',
        score: 2.1,
        notes: 'בעיות משמעת',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'שקד רוזנבלום',
        id: '579134',
        image: '',
        rank: 30,
        status: 'עבר',
        score: 4.4,
        notes: '',
        unit: 'מגלן',
    },
    {
        name: 'אורי בן דוד',
        id: '680245',
        image: '',
        rank: 31,
        status: 'עבר',
        score: 3.0,
        notes: '',
        unit: 'אגוז',
    },
    {
        name: 'רם אברהם',
        id: '791356',
        image: '',
        rank: 32,
        status: 'לא עבר',
        score: 2.8,
        notes: 'לא עמד בציפיות',
        unit: 'דובדבן',
    },
    {
        name: 'יובל לוי',
        id: '802467',
        image: '',
        rank: 33,
        status: 'עבר',
        score: 4.2,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'עומרי חודורוב',
        id: '913578',
        image: '',
        rank: 34,
        status: 'עבר',
        score: 3.9,
        notes: '',
        unit: 'מגלן',
    },
    {
        name: 'איתן רוזנברג',
        id: '024689',
        image: '',
        rank: 35,
        status: 'לא עבר',
        score: 2.6,
        notes: 'דרוש שיפור',
        unit: 'אגוז',
    },
    {
        name: 'עומרי גיל',
        id: '135790',
        image: '',
        rank: 36,
        status: 'עבר',
        score: 4.3,
        notes: 'מועמד מצטיין',
        unit: 'דובדבן',
    },
    {
        name: 'ניר סופר',
        id: '246801',
        image: '',
        rank: 37,
        status: 'עבר',
        score: 3.8,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'עדי אדרי',
        id: '357912',
        image: '',
        rank: 38,
        status: 'לא עבר',
        score: 2.7,
        notes: 'לא עמד בציפיות',
        unit: 'מגלן',
    },
    {
        name: 'אביאל פז',
        id: '468023',
        image: '',
        rank: 39,
        status: 'עבר',
        score: 4.5,
        notes: '',
        unit: 'אגוז',
    },
    {
        name: 'שני ניב',
        id: '579134',
        image: '',
        rank: 40,
        status: 'עבר',
        score: 3.4,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'עילי שמעוני',
        id: '680245',
        image: '',
        rank: 41,
        status: 'לא עבר',
        score: 2.5,
        notes: 'דרוש שיפור',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'יובל יוספי',
        id: '791356',
        image: '',
        rank: 42,
        status: 'עבר',
        score: 4.1,
        notes: '',
        unit: 'מגלן',
    },
    {
        name: 'מאור ברק',
        id: '802467',
        image: '',
        rank: 43,
        status: 'עבר',
        score: 3.6,
        notes: '',
        unit: 'אגוז',
    },
    {
        name: 'ניצן זיו',
        id: '913578',
        image: '',
        rank: 44,
        status: 'לא עבר',
        score: 2.4,
        notes: 'לא עמד בציפיות',
        unit: 'דובדבן',
    },
    {
        name: 'רוני לוי',
        id: '024689',
        image: '',
        rank: 45,
        status: 'עבר',
        score: 4.0,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'עומרי פישר',
        id: '135790',
        image: '',
        rank: 46,
        status: 'עבר',
        score: 3.3,
        notes: '',
        unit: 'מגלן',
    },
    {
        name: 'דביר חן',
        id: '246801',
        image: '',
        rank: 47,
        status: 'לא עבר',
        score: 2.9,
        notes: 'דרוש שיפור',
        unit: 'אגוז',
    },
    {
        name: 'אורי אטיאס',
        id: '357912',
        image: '',
        rank: 48,
        status: 'עבר',
        score: 4.2,
        notes: '',
        unit: 'דובדבן',
    },
    {
        name: 'שקד פרץ',
        id: '468023',
        image: '',
        rank: 49,
        status: 'עבר',
        score: 3.1,
        notes: '',
        unit: 'סיירת צנחנים',
    },
    {
        name: 'דביר שמואלי',
        id: '579134',
        image: '',
        rank: 50,
        status: 'לא עבר',
        score: 2.2,
        notes: 'בעיות משמעת',
        unit: 'מגלן',
    },
];