export type Instructor = {
    name: string;
    id: string;
    image: string;
    evaluatorNumber: number;
    evaluatedCount: number;
    detectedCount: number;
    detectedAndPassedCount: number;
    basicSeriesPassRate: string;
    averageScorePerCandidate: number;
    lastEvaluationDate: string;
};

export const mockInstructors: Instructor[] = [
    {
        "name": "טל מרציאנו",
        "id": "772596",
        "image": "",
        "evaluatorNumber": 100,
        "evaluatedCount": 211,
        "detectedCount": 83,
        "detectedAndPassedCount": 58,
        "basicSeriesPassRate": "70%",
        "averageScorePerCandidate": 4.6,
        "lastEvaluationDate": "09-03-2024 16:06"
    },
    {
        "name": "גיא בן עמי",
        "id": "148455",
        "image": "",
        "evaluatorNumber": 101,
        "evaluatedCount": 511,
        "detectedCount": 72,
        "detectedAndPassedCount": 11,
        "basicSeriesPassRate": "15%",
        "averageScorePerCandidate": 4.7,
        "lastEvaluationDate": "10-02-2024 14:15"
    },
    {
        "name": "עידן לוי",
        "id": "395346",
        "image": "",
        "evaluatorNumber": 102,
        "evaluatedCount": 325,
        "detectedCount": 90,
        "detectedAndPassedCount": 16,
        "basicSeriesPassRate": "18%",
        "averageScorePerCandidate": 4.8,
        "lastEvaluationDate": "04-04-2024 17:06"
    },
    {
        "name": "תומר ברק",
        "id": "204094",
        "image": "",
        "evaluatorNumber": 103,
        "evaluatedCount": 87,
        "detectedCount": 76,
        "detectedAndPassedCount": 50,
        "basicSeriesPassRate": "66%",
        "averageScorePerCandidate": 3.8,
        "lastEvaluationDate": "06-07-2024 14:49"
    },
    {
        "name": "נדב שגב",
        "id": "929884",
        "image": "",
        "evaluatorNumber": 104,
        "evaluatedCount": 600,
        "detectedCount": 26,
        "detectedAndPassedCount": 19,
        "basicSeriesPassRate": "73%",
        "averageScorePerCandidate": 3.0,
        "lastEvaluationDate": "03-12-2024 16:27"
    },
    {
        "name": "יהב ברק",
        "id": "745832",
        "image": "",
        "evaluatorNumber": 105,
        "evaluatedCount": 514,
        "detectedCount": 89,
        "detectedAndPassedCount": 29,
        "basicSeriesPassRate": "33%",
        "averageScorePerCandidate": 4.1,
        "lastEvaluationDate": "18-04-2024 17:30"
    },
    {
        "name": "אסף רוטמן",
        "id": "340208",
        "image": "",
        "evaluatorNumber": 106,
        "evaluatedCount": 550,
        "detectedCount": 79,
        "detectedAndPassedCount": 78,
        "basicSeriesPassRate": "99%",
        "averageScorePerCandidate": 3.9,
        "lastEvaluationDate": "25-09-2024 17:04"
    },
    {
        "name": "אור רוזן",
        "id": "689945",
        "image": "",
        "evaluatorNumber": 107,
        "evaluatedCount": 575,
        "detectedCount": 40,
        "detectedAndPassedCount": 33,
        "basicSeriesPassRate": "82%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "10-10-2024 12:07"
    },
    {
        "name": "אופק חדד",
        "id": "109056",
        "image": "",
        "evaluatorNumber": 108,
        "evaluatedCount": 313,
        "detectedCount": 47,
        "detectedAndPassedCount": 33,
        "basicSeriesPassRate": "70%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "30-05-2024 14:56"
    },
    {
        "name": "אבירם רוזן",
        "id": "578679",
        "image": "",
        "evaluatorNumber": 109,
        "evaluatedCount": 275,
        "detectedCount": 59,
        "detectedAndPassedCount": 10,
        "basicSeriesPassRate": "17%",
        "averageScorePerCandidate": 4.2,
        "lastEvaluationDate": "07-07-2024 16:10"
    },
    {
        "name": "אילון שגב",
        "id": "697792",
        "image": "",
        "evaluatorNumber": 110,
        "evaluatedCount": 497,
        "detectedCount": 18,
        "detectedAndPassedCount": 15,
        "basicSeriesPassRate": "83%",
        "averageScorePerCandidate": 4.4,
        "lastEvaluationDate": "20-07-2024 12:15"
    },
    {
        "name": "מאור ישראלי",
        "id": "872700",
        "image": "",
        "evaluatorNumber": 111,
        "evaluatedCount": 547,
        "detectedCount": 14,
        "detectedAndPassedCount": 9,
        "basicSeriesPassRate": "64%",
        "averageScorePerCandidate": 4.7,
        "lastEvaluationDate": "02-09-2024 12:57"
    },
    {
        "name": "עמית רוזן",
        "id": "684482",
        "image": "",
        "evaluatorNumber": 112,
        "evaluatedCount": 352,
        "detectedCount": 29,
        "detectedAndPassedCount": 26,
        "basicSeriesPassRate": "90%",
        "averageScorePerCandidate": 4.3,
        "lastEvaluationDate": "03-07-2024 14:51"
    },
    {
        "name": "אדם רוזן",
        "id": "352336",
        "image": "",
        "evaluatorNumber": 113,
        "evaluatedCount": 95,
        "detectedCount": 61,
        "detectedAndPassedCount": 45,
        "basicSeriesPassRate": "74%",
        "averageScorePerCandidate": 3.7,
        "lastEvaluationDate": "10-09-2024 16:32"
    },
    {
        "name": "עמרי קרני",
        "id": "388512",
        "image": "",
        "evaluatorNumber": 114,
        "evaluatedCount": 166,
        "detectedCount": 61,
        "detectedAndPassedCount": 35,
        "basicSeriesPassRate": "57%",
        "averageScorePerCandidate": 4.2,
        "lastEvaluationDate": "17-02-2024 14:06"
    },
    {
        "name": "עומר ישראלי",
        "id": "530823",
        "image": "",
        "evaluatorNumber": 115,
        "evaluatedCount": 216,
        "detectedCount": 58,
        "detectedAndPassedCount": 29,
        "basicSeriesPassRate": "50%",
        "averageScorePerCandidate": 4.7,
        "lastEvaluationDate": "20-04-2024 14:59"
    },
    {
        "name": "עומר ברק",
        "id": "924342",
        "image": "",
        "evaluatorNumber": 116,
        "evaluatedCount": 493,
        "detectedCount": 24,
        "detectedAndPassedCount": 5,
        "basicSeriesPassRate": "21%",
        "averageScorePerCandidate": 4.4,
        "lastEvaluationDate": "22-04-2024 17:37"
    },
    {
        "name": "יונתן רוזן",
        "id": "967622",
        "image": "",
        "evaluatorNumber": 117,
        "evaluatedCount": 134,
        "detectedCount": 88,
        "detectedAndPassedCount": 77,
        "basicSeriesPassRate": "88%",
        "averageScorePerCandidate": 4.6,
        "lastEvaluationDate": "25-06-2024 17:50"
    },
    {
        "name": "אור קרני",
        "id": "196786",
        "image": "",
        "evaluatorNumber": 118,
        "evaluatedCount": 321,
        "detectedCount": 98,
        "detectedAndPassedCount": 0,
        "basicSeriesPassRate": "0%",
        "averageScorePerCandidate": 4.1,
        "lastEvaluationDate": "06-06-2024 12:19"
    },
    {
        "name": "עומר דיין",
        "id": "860046",
        "image": "",
        "evaluatorNumber": 119,
        "evaluatedCount": 512,
        "detectedCount": 67,
        "detectedAndPassedCount": 34,
        "basicSeriesPassRate": "51%",
        "averageScorePerCandidate": 3.9,
        "lastEvaluationDate": "16-05-2024 17:28"
    },
    {
        "name": "מאור שמיר",
        "id": "519132",
        "image": "",
        "evaluatorNumber": 120,
        "evaluatedCount": 383,
        "detectedCount": 44,
        "detectedAndPassedCount": 35,
        "basicSeriesPassRate": "80%",
        "averageScorePerCandidate": 3.4,
        "lastEvaluationDate": "10-06-2024 14:20"
    },
    {
        "name": "אלון קרני",
        "id": "227930",
        "image": "",
        "evaluatorNumber": 121,
        "evaluatedCount": 107,
        "detectedCount": 43,
        "detectedAndPassedCount": 38,
        "basicSeriesPassRate": "88%",
        "averageScorePerCandidate": 4.4,
        "lastEvaluationDate": "25-08-2024 14:06"
    },
    {
        "name": "אילון אברג'ל",
        "id": "470434",
        "image": "",
        "evaluatorNumber": 122,
        "evaluatedCount": 225,
        "detectedCount": 88,
        "detectedAndPassedCount": 15,
        "basicSeriesPassRate": "17%",
        "averageScorePerCandidate": 4.9,
        "lastEvaluationDate": "03-08-2024 14:37"
    },
    {
        "name": "מאור ברק",
        "id": "817872",
        "image": "",
        "evaluatorNumber": 123,
        "evaluatedCount": 378,
        "detectedCount": 74,
        "detectedAndPassedCount": 33,
        "basicSeriesPassRate": "45%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "16-04-2024 14:00"
    },
    {
        "name": "אור בן דוד",
        "id": "924967",
        "image": "",
        "evaluatorNumber": 124,
        "evaluatedCount": 350,
        "detectedCount": 68,
        "detectedAndPassedCount": 56,
        "basicSeriesPassRate": "82%",
        "averageScorePerCandidate": 3.7,
        "lastEvaluationDate": "27-11-2024 16:06"
    },
    {
        "name": "אלון שגב",
        "id": "161032",
        "image": "",
        "evaluatorNumber": 125,
        "evaluatedCount": 394,
        "detectedCount": 80,
        "detectedAndPassedCount": 19,
        "basicSeriesPassRate": "24%",
        "averageScorePerCandidate": 3.3,
        "lastEvaluationDate": "08-08-2024 17:54"
    },
    {
        "name": "רם אליהו",
        "id": "830506",
        "image": "",
        "evaluatorNumber": 126,
        "evaluatedCount": 561,
        "detectedCount": 100,
        "detectedAndPassedCount": 53,
        "basicSeriesPassRate": "53%",
        "averageScorePerCandidate": 4.3,
        "lastEvaluationDate": "19-11-2024 12:17"
    },
    {
        "name": "אור דיין",
        "id": "468530",
        "image": "",
        "evaluatorNumber": 127,
        "evaluatedCount": 362,
        "detectedCount": 47,
        "detectedAndPassedCount": 31,
        "basicSeriesPassRate": "66%",
        "averageScorePerCandidate": 3.4,
        "lastEvaluationDate": "11-03-2024 17:10"
    },
    {
        "name": "עמית אליהו",
        "id": "232912",
        "image": "",
        "evaluatorNumber": 128,
        "evaluatedCount": 318,
        "detectedCount": 80,
        "detectedAndPassedCount": 62,
        "basicSeriesPassRate": "78%",
        "averageScorePerCandidate": 3.4,
        "lastEvaluationDate": "09-10-2024 14:46"
    },
    {
        "name": "רם אליהו",
        "id": "301860",
        "image": "",
        "evaluatorNumber": 129,
        "evaluatedCount": 205,
        "detectedCount": 96,
        "detectedAndPassedCount": 71,
        "basicSeriesPassRate": "74%",
        "averageScorePerCandidate": 4.0,
        "lastEvaluationDate": "27-02-2024 13:44"
    },
    {
        "name": "אדם ישראלי",
        "id": "496978",
        "image": "",
        "evaluatorNumber": 130,
        "evaluatedCount": 537,
        "detectedCount": 35,
        "detectedAndPassedCount": 4,
        "basicSeriesPassRate": "11%",
        "averageScorePerCandidate": 3.2,
        "lastEvaluationDate": "05-01-2024 13:00"
    },
    {
        "name": "עידן בן חיים",
        "id": "887731",
        "image": "",
        "evaluatorNumber": 131,
        "evaluatedCount": 563,
        "detectedCount": 36,
        "detectedAndPassedCount": 13,
        "basicSeriesPassRate": "36%",
        "averageScorePerCandidate": 4.9,
        "lastEvaluationDate": "21-11-2024 16:15"
    },
    {
        "name": "מאור קרני",
        "id": "717096",
        "image": "",
        "evaluatorNumber": 132,
        "evaluatedCount": 360,
        "detectedCount": 75,
        "detectedAndPassedCount": 43,
        "basicSeriesPassRate": "57%",
        "averageScorePerCandidate": 3.5,
        "lastEvaluationDate": "23-01-2024 14:13"
    },
    {
        "name": "יובל לוי",
        "id": "340382",
        "image": "",
        "evaluatorNumber": 133,
        "evaluatedCount": 338,
        "detectedCount": 91,
        "detectedAndPassedCount": 41,
        "basicSeriesPassRate": "45%",
        "averageScorePerCandidate": 4.8,
        "lastEvaluationDate": "27-04-2024 17:34"
    },
    {
        "name": "אבירם בן עמי",
        "id": "833058",
        "image": "",
        "evaluatorNumber": 134,
        "evaluatedCount": 300,
        "detectedCount": 34,
        "detectedAndPassedCount": 4,
        "basicSeriesPassRate": "12%",
        "averageScorePerCandidate": 3.8,
        "lastEvaluationDate": "02-04-2024 13:50"
    },
    {
        "name": "דקל חדד",
        "id": "517757",
        "image": "",
        "evaluatorNumber": 135,
        "evaluatedCount": 568,
        "detectedCount": 18,
        "detectedAndPassedCount": 9,
        "basicSeriesPassRate": "50%",
        "averageScorePerCandidate": 3.5,
        "lastEvaluationDate": "28-12-2024 12:16"
    },
    {
        "name": "אדם דיין",
        "id": "607940",
        "image": "",
        "evaluatorNumber": 136,
        "evaluatedCount": 51,
        "detectedCount": 89,
        "detectedAndPassedCount": 14,
        "basicSeriesPassRate": "16%",
        "averageScorePerCandidate": 4.3,
        "lastEvaluationDate": "01-03-2024 16:27"
    },
    {
        "name": "אסף ברק",
        "id": "932287",
        "image": "",
        "evaluatorNumber": 137,
        "evaluatedCount": 308,
        "detectedCount": 19,
        "detectedAndPassedCount": 7,
        "basicSeriesPassRate": "37%",
        "averageScorePerCandidate": 3.6,
        "lastEvaluationDate": "01-10-2024 14:44"
    },
    {
        "name": "איתי קרני",
        "id": "212840",
        "image": "",
        "evaluatorNumber": 138,
        "evaluatedCount": 480,
        "detectedCount": 23,
        "detectedAndPassedCount": 5,
        "basicSeriesPassRate": "22%",
        "averageScorePerCandidate": 5.0,
        "lastEvaluationDate": "02-07-2024 15:39"
    },
    {
        "name": "יהב לוי",
        "id": "211940",
        "image": "",
        "evaluatorNumber": 139,
        "evaluatedCount": 442,
        "detectedCount": 69,
        "detectedAndPassedCount": 19,
        "basicSeriesPassRate": "28%",
        "averageScorePerCandidate": 4.4,
        "lastEvaluationDate": "18-10-2024 16:10"
    },
    {
        "name": "עידן בן דוד",
        "id": "232430",
        "image": "",
        "evaluatorNumber": 140,
        "evaluatedCount": 384,
        "detectedCount": 85,
        "detectedAndPassedCount": 47,
        "basicSeriesPassRate": "55%",
        "averageScorePerCandidate": 4.9,
        "lastEvaluationDate": "10-12-2024 14:19"
    },
    {
        "name": "עמית גולן",
        "id": "672309",
        "image": "",
        "evaluatorNumber": 141,
        "evaluatedCount": 302,
        "detectedCount": 42,
        "detectedAndPassedCount": 42,
        "basicSeriesPassRate": "100%",
        "averageScorePerCandidate": 4.1,
        "lastEvaluationDate": "24-07-2024 17:20"
    },
    {
        "name": "רועי חדד",
        "id": "788028",
        "image": "",
        "evaluatorNumber": 142,
        "evaluatedCount": 311,
        "detectedCount": 51,
        "detectedAndPassedCount": 23,
        "basicSeriesPassRate": "45%",
        "averageScorePerCandidate": 4.0,
        "lastEvaluationDate": "22-11-2024 14:14"
    },
    {
        "name": "יהב בן דוד",
        "id": "419433",
        "image": "",
        "evaluatorNumber": 143,
        "evaluatedCount": 583,
        "detectedCount": 72,
        "detectedAndPassedCount": 44,
        "basicSeriesPassRate": "61%",
        "averageScorePerCandidate": 4.2,
        "lastEvaluationDate": "19-04-2024 16:29"
    },
    {
        "name": "עידו כהן",
        "id": "813564",
        "image": "",
        "evaluatorNumber": 144,
        "evaluatedCount": 138,
        "detectedCount": 99,
        "detectedAndPassedCount": 88,
        "basicSeriesPassRate": "89%",
        "averageScorePerCandidate": 4.2,
        "lastEvaluationDate": "28-06-2024 14:00"
    },
    {
        "name": "עידן שגב",
        "id": "352429",
        "image": "",
        "evaluatorNumber": 145,
        "evaluatedCount": 251,
        "detectedCount": 33,
        "detectedAndPassedCount": 22,
        "basicSeriesPassRate": "67%",
        "averageScorePerCandidate": 3.9,
        "lastEvaluationDate": "29-01-2024 15:19"
    },
    {
        "name": "גיא חדד",
        "id": "411210",
        "image": "",
        "evaluatorNumber": 146,
        "evaluatedCount": 137,
        "detectedCount": 57,
        "detectedAndPassedCount": 33,
        "basicSeriesPassRate": "58%",
        "averageScorePerCandidate": 3.1,
        "lastEvaluationDate": "04-10-2024 14:54"
    },
    {
        "name": "רועי לוי",
        "id": "419676",
        "image": "",
        "evaluatorNumber": 147,
        "evaluatedCount": 399,
        "detectedCount": 17,
        "detectedAndPassedCount": 0,
        "basicSeriesPassRate": "0%",
        "averageScorePerCandidate": 3.1,
        "lastEvaluationDate": "14-05-2024 14:13"
    },
    {
        "name": "איתי ישראלי",
        "id": "344077",
        "image": "",
        "evaluatorNumber": 148,
        "evaluatedCount": 176,
        "detectedCount": 83,
        "detectedAndPassedCount": 76,
        "basicSeriesPassRate": "92%",
        "averageScorePerCandidate": 3.8,
        "lastEvaluationDate": "05-12-2024 13:48"
    },
    {
        "name": "רם לוי",
        "id": "263619",
        "image": "",
        "evaluatorNumber": 149,
        "evaluatedCount": 135,
        "detectedCount": 11,
        "detectedAndPassedCount": 1,
        "basicSeriesPassRate": "9%",
        "averageScorePerCandidate": 4.3,
        "lastEvaluationDate": "24-08-2024 17:02"
    },
    {
        "name": "שון קרני",
        "id": "249030",
        "image": "",
        "evaluatorNumber": 150,
        "evaluatedCount": 571,
        "detectedCount": 56,
        "detectedAndPassedCount": 37,
        "basicSeriesPassRate": "66%",
        "averageScorePerCandidate": 3.3,
        "lastEvaluationDate": "02-01-2024 17:33"
    },
    {
        "name": "שחר חרמון",
        "id": "481403",
        "image": "",
        "evaluatorNumber": 151,
        "evaluatedCount": 83,
        "detectedCount": 44,
        "detectedAndPassedCount": 0,
        "basicSeriesPassRate": "0%",
        "averageScorePerCandidate": 4.8,
        "lastEvaluationDate": "10-08-2024 13:34"
    },
    {
        "name": "אור אליהו",
        "id": "764995",
        "image": "",
        "evaluatorNumber": 152,
        "evaluatedCount": 581,
        "detectedCount": 97,
        "detectedAndPassedCount": 43,
        "basicSeriesPassRate": "44%",
        "averageScorePerCandidate": 4.8,
        "lastEvaluationDate": "27-08-2024 17:23"
    },
    {
        "name": "מאור שמיר",
        "id": "361402",
        "image": "",
        "evaluatorNumber": 153,
        "evaluatedCount": 217,
        "detectedCount": 89,
        "detectedAndPassedCount": 73,
        "basicSeriesPassRate": "82%",
        "averageScorePerCandidate": 3.2,
        "lastEvaluationDate": "28-09-2024 12:39"
    },
    {
        "name": "אסף שמיר",
        "id": "828270",
        "image": "",
        "evaluatorNumber": 154,
        "evaluatedCount": 169,
        "detectedCount": 98,
        "detectedAndPassedCount": 70,
        "basicSeriesPassRate": "71%",
        "averageScorePerCandidate": 4.0,
        "lastEvaluationDate": "29-08-2024 15:04"
    },
    {
        "name": "רועי ישראלי",
        "id": "421077",
        "image": "",
        "evaluatorNumber": 155,
        "evaluatedCount": 209,
        "detectedCount": 79,
        "detectedAndPassedCount": 63,
        "basicSeriesPassRate": "80%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "21-08-2024 17:40"
    },
    {
        "name": "אופק אברג'ל",
        "id": "678635",
        "image": "",
        "evaluatorNumber": 156,
        "evaluatedCount": 60,
        "detectedCount": 17,
        "detectedAndPassedCount": 15,
        "basicSeriesPassRate": "88%",
        "averageScorePerCandidate": 3.8,
        "lastEvaluationDate": "09-04-2024 16:34"
    },
    {
        "name": "מאור רוזן",
        "id": "932587",
        "image": "",
        "evaluatorNumber": 157,
        "evaluatedCount": 377,
        "detectedCount": 66,
        "detectedAndPassedCount": 59,
        "basicSeriesPassRate": "89%",
        "averageScorePerCandidate": 4.1,
        "lastEvaluationDate": "13-09-2024 12:51"
    },
    {
        "name": "יובל שגב",
        "id": "221650",
        "image": "",
        "evaluatorNumber": 158,
        "evaluatedCount": 326,
        "detectedCount": 11,
        "detectedAndPassedCount": 3,
        "basicSeriesPassRate": "27%",
        "averageScorePerCandidate": 3.8,
        "lastEvaluationDate": "12-12-2024 14:38"
    },
    {
        "name": "עמית קרני",
        "id": "180376",
        "image": "",
        "evaluatorNumber": 159,
        "evaluatedCount": 448,
        "detectedCount": 66,
        "detectedAndPassedCount": 52,
        "basicSeriesPassRate": "79%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "20-10-2024 17:47"
    },
    {
        "name": "יהב קרני",
        "id": "187340",
        "image": "",
        "evaluatorNumber": 160,
        "evaluatedCount": 323,
        "detectedCount": 10,
        "detectedAndPassedCount": 9,
        "basicSeriesPassRate": "90%",
        "averageScorePerCandidate": 4.8,
        "lastEvaluationDate": "15-06-2024 12:20"
    },
    {
        "name": "יונתן בן עמי",
        "id": "177614",
        "image": "",
        "evaluatorNumber": 161,
        "evaluatedCount": 232,
        "detectedCount": 68,
        "detectedAndPassedCount": 23,
        "basicSeriesPassRate": "34%",
        "averageScorePerCandidate": 4.6,
        "lastEvaluationDate": "03-01-2024 17:23"
    },
    {
        "name": "אדם כהן",
        "id": "208861",
        "image": "",
        "evaluatorNumber": 162,
        "evaluatedCount": 55,
        "detectedCount": 13,
        "detectedAndPassedCount": 11,
        "basicSeriesPassRate": "85%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "11-09-2024 17:52"
    },
    {
        "name": "רועי דיין",
        "id": "107567",
        "image": "",
        "evaluatorNumber": 163,
        "evaluatedCount": 205,
        "detectedCount": 58,
        "detectedAndPassedCount": 9,
        "basicSeriesPassRate": "16%",
        "averageScorePerCandidate": 4.0,
        "lastEvaluationDate": "24-02-2024 13:46"
    },
    {
        "name": "עידן ישראלי",
        "id": "820241",
        "image": "",
        "evaluatorNumber": 164,
        "evaluatedCount": 108,
        "detectedCount": 55,
        "detectedAndPassedCount": 16,
        "basicSeriesPassRate": "29%",
        "averageScorePerCandidate": 4.5,
        "lastEvaluationDate": "25-10-2024 15:35"
    },
    {
        "name": "שון בן עמי",
        "id": "422177",
        "image": "",
        "evaluatorNumber": 165,
        "evaluatedCount": 156,
        "detectedCount": 83,
        "detectedAndPassedCount": 66,
        "basicSeriesPassRate": "80%",
        "averageScorePerCandidate": 3.6,
        "lastEvaluationDate": "22-03-2024 17:55"
    },
    {
        "name": "דקל דיין",
        "id": "332512",
        "image": "",
        "evaluatorNumber": 166,
        "evaluatedCount": 180,
        "detectedCount": 53,
        "detectedAndPassedCount": 48,
        "basicSeriesPassRate": "91%",
        "averageScorePerCandidate": 3.9,
        "lastEvaluationDate": "21-10-2024 14:23"
    },
    {
        "name": "טל חדד",
        "id": "405170",
        "image": "",
        "evaluatorNumber": 167,
        "evaluatedCount": 385,
        "detectedCount": 47,
        "detectedAndPassedCount": 19,
        "basicSeriesPassRate": "40%",
        "averageScorePerCandidate": 4.8,
        "lastEvaluationDate": "01-02-2024 13:08"
    },
    {
        "name": "יובל בן עמי",
        "id": "875051",
        "image": "",
        "evaluatorNumber": 168,
        "evaluatedCount": 262,
        "detectedCount": 91,
        "detectedAndPassedCount": 56,
        "basicSeriesPassRate": "62%",
        "averageScorePerCandidate": 4.9,
        "lastEvaluationDate": "06-10-2024 16:33"
    },
    {
        "name": "אדם שגב",
        "id": "177220",
        "image": "",
        "evaluatorNumber": 169,
        "evaluatedCount": 334,
        "detectedCount": 30,
        "detectedAndPassedCount": 6,
        "basicSeriesPassRate": "20%",
        "averageScorePerCandidate": 4.7,
        "lastEvaluationDate": "07-04-2024 14:01"
    },
];